language: java
jdk:
  - oraclejdk8
env:
  - TERM=dumb
after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: bintray
  file: .bintray
  user: ""
  key: ""
  dry-run: true


